

name: "Linting"
on:
  pull_request:
    branches:
      - master
    tags:
      - ci
      - lint

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
          cache-dependency-path: 'tools/requirements.txt'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.4

      - name: Install dependencies
        run: |
          pip install -r tools/requirements.txt

      - name: Boilerplate
        id: boilerplate
        run: |
          python3 tools/check_boilerplate.py $GITHUB_WORKSPACE

      - name: Terraform Linting Check
        id: fmt
        run: |
          terraform fmt -recursive -check -diff $GITHUB_WORKSPACE

      - name: Check documentation
        id: documentation-fabric
        run: |
          python3 tools/check_documentation.py --show-diffs modules fast modules

      - name: Check documentation links
        id: documentation-links-fabric
        run: |
          python3 tools/check_links.py .

      - name: Check name length (fast)
        id: name-length-fast
        run: |
          python3 tools/check_names.py --prefix-length=10 fast/stages

      - name: Check python formatting
        id: yapf
        run: |
          yapf --style="{based_on_style: google, indent_width: 2, SPLIT_BEFORE_NAMED_ASSIGNS: false}" -p -d \
            tools/*.py \
            modules/src/*py \
            modules/src/plugins/*py

      - name: Check blueprint metadata
        id: metadata
        run: |
          python tools/validate_metadata.py -v modules
